manifest = "c2b7e3a806cd0cce3f0769ee5662e5f4ba6e810ae297f8712ecb0c3dc96a4a4f"

[[dependency]]
package = "github.com/buckaroo-pm/madler-zlib"
target = "//:zlib"

[[dependency]]
package = "github.com/buckaroo-pm/openssl"
target = "//:openssl"

[lock."github.com/buckaroo-pm/madler-zlib"]
versions = [ "1.2.11" ]
revision = "94a70f3274f15bf98b472178e91fd57a6e6c53d8"

[lock."github.com/buckaroo-pm/openssl"]
versions = [ "tag=1.0.2j" ]
revision = "e61671249ee5dfa59b663d135b64dd6fe9efe9d0"
